name: GA-Interview
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

#job one 
jobs:
  build:
    runs-on: ubuntu-latest #github runner 
    steps:
  # need checkout before using compose-action
    - uses: actions/checkout@v3         #user checkout actions to checkout
    - uses: isbang/compose-action@v1.4.1  #uses compose actions
      with:
        compose-file: "./docker-compose.yml"
        #down-flags: "--volumes"
        services: |
          node-app
          angular
          sql-db


      ## *********** To publish images to docker hub *********** ##
  # Docker: 
  #   runs-on: ubuntu-latest
  #   steps:
  #    - uses: actions/checkout@v2  
  #    - name: Set up Docker Buildx
  #      uses: docker/setup-buildx-action@v2
      
  #    - name: Login to Docker Hub
  #      uses: docker/login-action@v2
  #      with:
  #          username: ${{ secrets.DOCKER_USERNAME }}
  #          password: ${{ secrets.DOCKER_PASSWORD }}   
  #    - name: Build and push
  #      uses: docker/build-push-action@v4
  #      with:
  #           push: true
  #           tags: Dockerhub-username/repo:tagversion         